version: '3'
services:
    rabbitmq:
        image: rabbitmq
        ports:
            - "5672:5672"
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
    redis:
        image: redis
        ports:
            - "6379:6379"
    postgres:
        image: postgres
        environment:
           - POSTGRES_PASSWORD=password
           - POSTGRES_USER=cfd_partner_finder
           - POSTGRES_DB=cfd_partner_finder
        ports:
            - "5432:5432"
